config/routes.rb
Rails.application.routes.draw do
  resources :owls
  resources :hedgehogs
  resources :chicks
  resources :dogs
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: redirect("/cats")
  # root "articles#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_to(path, emoji, text)
    classes = %w[my-1 nav-link text-white]
    classes << "active" if current_page?(path)

    link_to(path, class: classes) do
      tag.span(class: "me-2") { emoji } + tag.span { text }
    end
  end

  def icon(icon_name)
    tag.i(class: ["bi", "bi-#{icon_name}"])
  end

  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: "me-2") + tag.span(text)
  end
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= alert %>
  </div>
<% end %>

app/views/application/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 py-3 px-3 bg-dark text-white vh-100">
  <div class="d-flex align-items-center justify-content-center py-2">
    <%= link_to "AMS", root_path, class: "text-white display-6 text-decoration-none" %>
  </div>
  <hr />

  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= sidebar_link_to(cats_path, "🐱", "ねこ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(dogs_path, "🐶", "いぬ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(chicks_path, "🐣", "ひよこ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(hedgehogs_path, "🦔", "ハリネズミ") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(owls_path, "🦉", "フクロウ") %>
    </li>
  </ul>
</div>